#pragma once
#define NUMBER_OF_MAIN_MENU_BUTTONS 3
#define NUMBER_OF_SETTINGS_BUTTONS 8
#define AUDIO_ON 1
#define AUDIO_OFF 0
#define MAIN_MENU_PROGRAM_STATE 0
#define GAME_PROGRAM_STATE 1
#define SETTINGS_PROGRAM_STATE 2
#define QUIT_PROGRAM_STATE 3
#define MUSIC_IS_NOT_PLAYING 0
#define MUSIC_IS_PLAYING 1
#define DRAW 1
#define RED_WINS 2
#define GREEN_WINS 3